### PR TITLE
Hid information that should be secure and other refactors

### PR DESCRIPTION
**Pull request by kn9ts**
Hi, I've done a couple of refractors
- prettified the code base
- created a `dotenv.php` file to load up secure variables into the environment before computation
- added `.gitignore` to hide the .env file for security purposes
- created a `.env` file which will have the secure information to be loaded.

I shall email you the `.env` right after this pull request

### CODE REVIEW

**Comment by icrackthecode** [comment]
i have checked out the commits, look pretty good. However, my concern is will it not make it a little complex. My idea was that any one without any form of coding experience could simply add the two files and they are good to go.

**Comment by kn9ts** [comment]
The only and major change is the requirement of a `.env` which is not tracked by the repo since details such as `PASSKEY`, `TRANSACTION_PASSWORD` need to hidden for security purposes. And security is key to any architecture esp. a finance handler.

**Comment by icrackthecode** [comment]
I agree. Okay merging ASAP!

**Comment by icrackthecode** [comment]
Hey realized that the file has some issue on taking one of the environmental parameters.

**Comment by kn9ts** [comment]
Which file? Could you comment on the file itself on the erroneous line if you'd like to discuss about before fixing the issue?

**Comment by icrackthecode** [comment]
Sure let me make changes on it. Also the .env file may be security issue to newbies since it is recognized as a text file by default it is visible hence leading to a credential leak. Will convert it into a .php file which is more secure.

**Pull request merged**
